// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADi_rz82lCWYZ0v4qLTtlXV1I0EsE2GNE',
    appId: '1:1089166131283:web:7c1cceaa8e0f8f792846a6',
    messagingSenderId: '1089166131283',
    projectId: 'pamelesxi-5182d',
    authDomain: 'pamelesxi-5182d.firebaseapp.com',
    storageBucket: 'pamelesxi-5182d.appspot.com',
    measurementId: 'G-9LTCHXZKCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcl3SRRDIMRF4_QmLMZh6rjUbLapPTJ8U',
    appId: '1:1089166131283:android:3503a3ff115e822d2846a6',
    messagingSenderId: '1089166131283',
    projectId: 'pamelesxi-5182d',
    storageBucket: 'pamelesxi-5182d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0CY961UYEZX42g8FmbFkCECzF1aYMOz4',
    appId: '1:1089166131283:ios:b4a40170a3abb8982846a6',
    messagingSenderId: '1089166131283',
    projectId: 'pamelesxi-5182d',
    storageBucket: 'pamelesxi-5182d.appspot.com',
    iosBundleId: 'com.example.studentRestaurantUoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0CY961UYEZX42g8FmbFkCECzF1aYMOz4',
    appId: '1:1089166131283:ios:b4a40170a3abb8982846a6',
    messagingSenderId: '1089166131283',
    projectId: 'pamelesxi-5182d',
    storageBucket: 'pamelesxi-5182d.appspot.com',
    iosBundleId: 'com.example.studentRestaurantUoi',
  );
}
