name: student_restaurant_uoi
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.2+7

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  http: ^0.13.5
  provider: ^6.0.3
  intl: ^0.17.0
  table_calendar: ^3.0.7
  flutter_launcher_icons: ^0.10.0
  url_launcher: ^6.1.5
  sqflite: ^2.0.3+1
  path: ^1.8.1
  firebase_messaging: ^14.6.8
  firebase_core: ^2.16.0
  flutter_local_notifications: ^15.1.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  change_app_package_name: ^1.1.0
  firebase_analytics: ^10.5.0
  equatable: ^2.0.5
  mocktail: ^1.0.1
  dartz: ^0.10.1
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/icon.png
    - assets/icons/efood.png
    - assets/images/
